name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - name: PHPStan
        uses: php-actions/phpstan@v3
        with:
          path: src/
      - name: PHPUnit
        uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml
